name: Cosmic Vanilla
id: cosmicvanilla

stages:
- id: build
  base: ghcr.io/vanilla-os/core:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
    - sed -i '4,10d' /etc/profile
    - apt update
    - apt clean
    - apt-mark hold snapd gnome-software-plugin-snap
    - apt -y install squashfs-tools minisign

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
      checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
    - cp /sources/vanilla-tools/vanilla-tools/cur-gpu /usr/bin/cur-gpu
    - chmod +x /usr/bin/lpkg
    - chmod +x /usr/bin/cur-gpu

  - name: packages-modules
    type: includes
    includes:
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-apx-gui.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-backgrounds.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-desktop-base.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-first-setup.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-prime-utility.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-sideload.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-system-operator.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-tour.yml
      - gh:vanilla-os/desktop-image:main:modules/00-vanilla-updates-utility.yml
      - gh:vanilla-os/desktop-image:main:modules/03-fswarn.yml
      - modules/01-cosmic.yml
      - gh:vanilla-os/desktop-image:main:modules/10-vanilla-abroot-rollback-notifier.yml
      - gh:vanilla-os/desktop-image:main:modules/35-nautilus-terminal-rightclick.yml
      - gh:vanilla-os/desktop-image:main:modules/50-laptop-goodies.yml
      - gh:vanilla-os/desktop-image:main:modules/60-media.yml
      - gh:vanilla-os/desktop-image:main:modules/80-printers.yml
      - gh:vanilla-os/desktop-image:main:modules/90-3d-utils.yml
      - gh:vanilla-os/desktop-image:main:modules/100-accessibility.yml
      - gh:vanilla-os/desktop-image:main:modules/110-fonts.yml
      - gh:vanilla-os/desktop-image:main:modules/120-network.yml
      - gh:vanilla-os/desktop-image:main:modules/121-disable-ssh-daemon.yml
      - gh:vanilla-os/desktop-image:main:modules/130-plymouth.yml
      - gh:vanilla-os/desktop-image:main:modules/131-plymouth-theme-vanilla.yml
      - gh:vanilla-os/desktop-image:main:modules/140-password.yml
      - gh:vanilla-os/desktop-image:main:modules/160-utilities.yml
      - gh:vanilla-os/desktop-image:main:modules/170-gnome-software-vso-plugin.yml
      - gh:vanilla-os/desktop-image:main:modules/200-gnome-common.yml
      - gh:vanilla-os/desktop-image:main:modules/210-libs-extra.yml
      - gh:vanilla-os/desktop-image:main:modules/300-hide-image-magick.yml
      - modules/900-nvidia-drivers.yml
      - gh:vanilla-os/desktop-image:main:modules/997-ensure-exec-hooks.yml
      - modules/998-vanilla-cleanup.yml
      - gh:vanilla-os/desktop-image:main:modules/999-pkg-cleanup.yml
      - gh:vanilla-os/desktop-image:main:modules/999-clear-first-setup-steps-unit.yml

  - name: blackbox-rescue
    type: shell
    commands:
    - echo "\nActions=rescue;\n[Desktop Action rescue]\nName=Rescue Mode\nExec=blackbox-terminal -c /bin/bash\nIcon=com.raggesilver.BlackBox" >> /usr/share/applications/com.raggesilver.BlackBox.desktop

  - name: fix-gdm-permissions-service
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/multi-user.target.wants/
    - ln -s /usr/lib/systemd/system/fix-gdm-permissions.service /etc/systemd/system/multi-user.target.wants/

  - name: gnome-software-setup
    type: shell
    commands:
    - rm /usr/lib/*/gnome-software/plugins-*/libgs_plugin_packagekit.so

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
